/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vladislav Laryushin (https://sketchfab.com/Zorg741)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/birds-b2c32bd4b78747e5b061c8348128e205
Title: Birds
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bird(props) {
  const { nodes, materials } = useGLTF('/models/birds.glb')
  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2, -0.4, -1]} scale={props.scale || 0.8} position={props.position || [1.2, 0.5, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
      />
    </group>
  )
}

useGLTF.preload('/models/birds.glb')
